"""init tables

Revision ID: 101a18805a91
Revises: 
Create Date: 2025-12-12 19:25:27.339300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '101a18805a91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_key', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('arch', sa.String(length=32), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_key')
    )
    op.create_index('ix_devices_last_seen_at', 'devices', ['last_seen_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_policies_is_active', 'policies', ['is_active'], unique=False)
    op.create_table('enroll_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_device_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['used_by_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_enroll_tokens_expires_at', 'enroll_tokens', ['expires_at'], unique=False)
    op.create_table('policy_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('audit', 'enforce', name='assignmentmode'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'policy_id', name='uq_policy_assignment_device_policy')
    )
    op.create_index('ix_policy_assignments_device_id', 'policy_assignments', ['device_id'], unique=False)
    op.create_index('ix_policy_assignments_policy_id', 'policy_assignments', ['policy_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'partial', name='runstatus'), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_device_id_started_at', 'runs', ['device_id', 'started_at'], unique=False)
    op.create_table('run_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('compliant_before', sa.Boolean(), nullable=True),
    sa.Column('compliant_after', sa.Boolean(), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('reboot_required', sa.Boolean(), nullable=False),
    sa.Column('status_detect', sa.Enum('not_run', 'ok', 'fail', 'skipped', name='stepstatus'), nullable=False),
    sa.Column('status_remediate', sa.Enum('not_run', 'ok', 'fail', 'skipped', name='stepstatus'), nullable=False),
    sa.Column('status_validate', sa.Enum('not_run', 'ok', 'fail', 'skipped', name='stepstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_items_resource_type_id', 'run_items', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_run_items_run_id', 'run_items', ['run_id'], unique=False)
    op.create_table('log_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('run_item_id', sa.UUID(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', name='loglevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_item_id'], ['run_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_events_run_id_ts', 'log_events', ['run_id', 'ts'], unique=False)
    op.create_index('ix_log_events_run_item_id', 'log_events', ['run_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_events_run_item_id', table_name='log_events')
    op.drop_index('ix_log_events_run_id_ts', table_name='log_events')
    op.drop_table('log_events')
    op.drop_index('ix_run_items_run_id', table_name='run_items')
    op.drop_index('ix_run_items_resource_type_id', table_name='run_items')
    op.drop_table('run_items')
    op.drop_index('ix_runs_device_id_started_at', table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_policy_assignments_policy_id', table_name='policy_assignments')
    op.drop_index('ix_policy_assignments_device_id', table_name='policy_assignments')
    op.drop_table('policy_assignments')
    op.drop_index('ix_enroll_tokens_expires_at', table_name='enroll_tokens')
    op.drop_table('enroll_tokens')
    op.drop_index('ix_policies_is_active', table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_devices_last_seen_at', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
