"""add effective_policy_hash to runs

Revision ID: 51a4f5ea4b18
Revises: 101a18805a91
Create Date: 2025-12-12 22:14:14.931312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a4f5ea4b18'
down_revision: Union[str, None] = '101a18805a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('effective_policy_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'effective_policy_hash')
    # ### end Alembic commands ###
